// User Types

export const GET_USER = 'GET_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';

// Work Types

export const GET_WORKS_BY_NEWEST = 'GET_WORKS_BY_NEWEST';
export const GET_WORKS_BY_FOLLOWING = 'GET_WORKS_BY_FOLLOWING';
export const GET_WORK = 'GET_WORK';

export const ADD_COMMENT = 'ADD_COMMENT';
export const LIKE_UNLIKE_WORK = 'LIKE_UNLIKE_WORK';

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SHOW_FOLLOWING = 'SHOW_FOLLOWING';
export const SHOW_LATEST = 'SHOW_LATEST';

// Profile Types

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_WORKS = 'GET_PROFILE_WORKS';
export const GET_PROFILE_FAVOURITES = 'GET_PROFILE_FAVOURITES';
export const RELOAD_PROFILE = 'RELOAD_PROFILE';
